/*!
 * RENUVOL — script for a Tilda T123 block.
 *
 * Generated by scripts/build-tilda.mjs. Do not edit by hand: change the
 * source in src/ and re-run the script.
 *
 * Every selector is scoped to #renuvol-site. Asset URLs are {{PLACEHOLDERS}}
 * — see asset-map.md.
 */
(function () {
'use strict';

/* ---- src/js/root.js ----------------------------------------------------- */
/**
 * The site's scope root.
 *
 * Standalone and embedded, everything the site owns lives inside
 * `#renuvol-site`. Two things follow from that:
 *
 * 1. Element lookups are scoped to the wrapper, so an embed can never reach
 *    into the host page's markup (or be confused by it).
 * 2. Page state — `data-rv-ground`, `--rv-page`, `--rv-mx/--rv-my`,
 *    `.rv-static`, `.rv-no-js` — is written to the wrapper rather than to
 *    `<html>`, which on a Tilda page is not ours to touch. Custom properties
 *    inherit, so everything inside reads them exactly as before.
 *
 * The fallback to `document.documentElement` keeps the modules usable if the
 * wrapper is ever missing; nothing then breaks, it just widens the scope.
 */

let cached = null;

/** The wrapper, resolved once. */
function siteRoot() {
  if (cached && cached.isConnected) return cached;
  cached = document.getElementById('renuvol-site') || document.documentElement;
  return cached;
}

/** Reset the cache — only needed if the wrapper is replaced at runtime. */
function resetSiteRoot() {
  cached = null;
}

/** Scoped `querySelector`. */
function q(selector) {
  return siteRoot().querySelector(selector);
}

/** Scoped `querySelectorAll`, as an array. */
function qa(selector) {
  return Array.from(siteRoot().querySelectorAll(selector));
}

/* ---- src/js/scroll.js --------------------------------------------------- */
/**
 * Scroll engine.
 *
 * One rAF loop drives every scroll-linked value on the page. Scenes publish
 * their own progress as `--rv-p` (0..1) on their root element; everything
 * visual is then expressed in CSS against that variable. Nothing here writes
 * layout-triggering properties, and the loop only runs while at least one
 * scene is on screen.
 *
 * Deliberately no scroll event listener for continuous values, per the
 * device contract in docs/motion-spec.md.
 */

const clamp01 = (n) => (n < 0 ? 0 : n > 1 ? 1 : n);

/**
 * Cue window: "from to [rampIn rampOut]", all in scene progress.
 * A third value of 0 makes a "greet" cue — already at full opacity when the
 * scene begins, so the first screen a visitor sees is never blank.
 */
function parseCue(value) {
  const parts = String(value).trim().split(/\s+/).map(Number);
  const from = Number.isFinite(parts[0]) ? parts[0] : 0;
  const to = Number.isFinite(parts[1]) ? parts[1] : 1;
  const span = Math.max(to - from, 0.0001);
  const rampIn = Number.isFinite(parts[2]) ? parts[2] : span * 0.3;
  const rampOut = Number.isFinite(parts[3]) ? parts[3] : span * 0.3;
  return { from, to, rampIn, rampOut, hold: parts.length === 1 };
}

function cueOpacity(p, cue) {
  if (cue.hold) {
    // Single value: fade in and stay. Only the last cue of a scene should.
    return cue.rampIn > 0 ? clamp01((p - cue.from) / cue.rampIn) : p >= cue.from ? 1 : 0;
  }
  // Strict comparisons: with rampIn 0 (a "greet" cue) p === from must read as
  // fully visible, not as the very start of a fade that never happened.
  if (p < cue.from - cue.rampIn || p > cue.to + cue.rampOut) return 0;
  if (p < cue.from) return cue.rampIn > 0 ? clamp01((p - (cue.from - cue.rampIn)) / cue.rampIn) : 1;
  if (p > cue.to) return cue.rampOut > 0 ? clamp01((cue.to + cue.rampOut - p) / cue.rampOut) : 1;
  return 1;
}

function createScrollEngine({ reducedMotion = false } = {}) {
  const scenes = [];
  const subscribers = new Set();
  let running = false;
  let frame = 0;

  const root = siteRoot();

  // Reduced motion: pinned scenes are not given their travel height at all.
  // Holding a frozen frame for three viewports is dead scroll, so the stages
  // become ordinary sections and their content is shown in full instead.
  if (reducedMotion) root.classList.add('rv-static');

  qa('[data-rv-scene]').forEach((el) => {
    const span = parseFloat(el.dataset.rvSpan || '0');
    const stage = el.querySelector('[data-rv-stage]');

    // A scene with a span is a pinned scene: give the section the height that
    // its stage needs to travel through.
    if (span > 0 && stage && !reducedMotion) {
      el.style.height = `${span * 100}vh`;
    }

    scenes.push({
      el,
      stage,
      pinned: Boolean(span > 0 && stage),
      ground: el.dataset.rvGround || 'pearl',
      cues: Array.from(el.querySelectorAll('[data-rv-cue]')).map((node) => {
        // A faded cue is invisible but still hit-testable, and several of
        // them are full-width blocks laid over live controls. Start them
        // inert; the loop restores hit-testing as they come in. Under
        // reduced motion every cue is shown at once and never fades, so
        // there is nothing to make inert.
        if (!reducedMotion) node.style.pointerEvents = 'none';
        return { node, cue: parseCue(node.dataset.rvCue), last: -1 };
      }),
      visible: false,
      p: -1,
    });
  });

  // Only run the loop for scenes actually on screen.
  const io = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        const scene = scenes.find((s) => s.el === entry.target);
        if (scene) scene.visible = entry.isIntersecting;
      });
      if (scenes.some((s) => s.visible)) start();
    },
    { rootMargin: '20% 0px 20% 0px' }
  );
  scenes.forEach((s) => io.observe(s.el));

  // Ground drift: whichever scene owns the middle of the viewport sets the
  // page ground, so colour changes hand off between scenes instead of
  // switching at hard section boundaries.
  //
  // This is resolved per frame from the scene rects rather than by an
  // IntersectionObserver on a thin centre band. The observer version fired
  // only on intersection *changes*, so a chapter whose entry event coincided
  // with a neighbour's — or any chapter re-entered while scrolling up, where
  // no new event fires at all — was silently skipped. Three of the nine
  // chapters never appeared. Reading the midpoint each frame is
  // deterministic, symmetric in both directions, and costs one pass over a
  // list the loop already walks.
  let currentGround = '';

  function updateGround() {
    const mid = (window.innerHeight || document.documentElement.clientHeight) / 2;
    let pick = null;

    for (const scene of scenes) {
      if (!scene.visible) continue;
      const rect = scene.el.getBoundingClientRect();
      // Later sections win an overlap, so the ground advances with the page.
      if (rect.top <= mid && rect.bottom > mid) pick = scene;
    }

    if (pick && pick.ground !== currentGround) {
      currentGround = pick.ground;
      root.dataset.rvGround = pick.ground;
    }
  }

  function progressOf(scene) {
    const rect = scene.el.getBoundingClientRect();
    const vh = window.innerHeight || document.documentElement.clientHeight;

    if (scene.pinned) {
      // Travel is the section height minus the one viewport the stage holds.
      const travel = Math.max(rect.height - vh, 1);
      return clamp01(-rect.top / travel);
    }
    // Unpinned scenes report their pass through the viewport, which is enough
    // for ambient effects; they generally do not use cues.
    const travel = Math.max(rect.height + vh, 1);
    return clamp01((vh - rect.top) / travel);
  }

  let lastPage = -1;

  /**
   * Progress through the site, published on the wrapper as --rv-page. The
   * fixed atmosphere layer reads it, which is what carries the same forms
   * through the whole document instead of restarting them per section.
   *
   * Measured against the wrapper's own extent, not the document's. Embedded
   * in a Tilda page there can be blocks above and below the site, and
   * measuring the document would hand the atmosphere a range that is mostly
   * somebody else's content.
   */
  function publishPageProgress() {
    const vh = window.innerHeight || document.documentElement.clientHeight;
    const rect = root.getBoundingClientRect();
    const travel = Math.max(rect.height - vh, 1);
    const p = clamp01(-rect.top / travel);
    if (Math.abs(p - lastPage) < 0.0015) return;
    lastPage = p;
    root.style.setProperty('--rv-page', p.toFixed(4));
  }

  function tick() {
    frame = 0;
    let active = false;

    publishPageProgress();

    updateGround();

    for (const scene of scenes) {
      if (!scene.visible) continue;
      active = true;

      const p = progressOf(scene);
      if (Math.abs(p - scene.p) > 0.0004) {
        scene.p = p;
        scene.el.style.setProperty('--rv-p', p.toFixed(4));

        for (const entry of scene.cues) {
          const o = cueOpacity(p, entry.cue);
          if (Math.abs(o - entry.last) > 0.004) {
            const wasInert = entry.last <= 0.02;
            entry.last = o;
            entry.node.style.setProperty('--rv-o', o.toFixed(3));

            const inert = !reducedMotion && o <= 0.02;
            if (inert !== wasInert) entry.node.style.pointerEvents = inert ? 'none' : '';
          }
        }

        subscribers.forEach((fn) => fn(scene.el, p));
      }
    }

    if (active) {
      frame = requestAnimationFrame(tick);
    } else {
      running = false;
    }
  }

  function start() {
    if (running || reducedMotion === 'freeze') return;
    running = true;
    frame = requestAnimationFrame(tick);
  }

  /** Subscribe to per-scene progress: fn(sceneEl, progress). */
  function onProgress(fn) {
    subscribers.add(fn);
    return () => subscribers.delete(fn);
  }

  function destroy() {
    if (frame) cancelAnimationFrame(frame);
    io.disconnect();
    groundIo.disconnect();
    subscribers.clear();
    running = false;
  }

  start();

  return { onProgress, destroy, scenes };
}

/** Enter-on-scroll for ordinary content. Fires once per element. */
function initReveals() {
  const items = qa('[data-rv-reveal]');
  if (!items.length) return;

  if (!('IntersectionObserver' in window)) {
    items.forEach((el) => el.classList.add('is-in'));
    return;
  }

  const io = new IntersectionObserver(
    (entries, observer) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        entry.target.classList.add('is-in');
        observer.unobserve(entry.target);
      });
    },
    { rootMargin: '0px 0px -12% 0px', threshold: 0.15 }
  );

  // Stagger siblings so a group arrives in sequence rather than all at once.
  const groups = new Map();
  items.forEach((el) => {
    const parent = el.parentElement;
    const index = groups.get(parent) || 0;
    groups.set(parent, index + 1);
    if (index) el.style.setProperty('--rv-delay', `${Math.min(index * 70, 280)}ms`);
    io.observe(el);
  });
}

/**
 * In-page anchors.
 *
 * Handled in JS rather than by `html { scroll-behavior: smooth }` for two
 * reasons. Embedded in Tilda the site does not own `<html>`, so the CSS
 * property is the host's to set; and a fixed header means the browser's own
 * anchor scrolling lands the target underneath it. Doing it here keeps the
 * behaviour identical in both contexts and puts the target where it belongs.
 *
 * Only links whose target is inside the wrapper are intercepted — anything
 * pointing at the host page is left alone.
 */
function initAnchors() {
  const root = siteRoot();
  const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  const onClick = (event) => {
    if (event.defaultPrevented || event.button !== 0) return;
    if (event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return;

    const link = event.target.closest?.('a[href^="#"]');
    if (!link || !root.contains(link)) return;

    const id = link.getAttribute('href').slice(1);
    if (!id) return;

    let target;
    try {
      target = root.querySelector(`#${CSS.escape(id)}`);
    } catch {
      return;
    }
    if (!target) return;

    event.preventDefault();

    const header = q('[data-rv-header]');
    const offset = header ? header.getBoundingClientRect().height : 0;
    const top = target.getBoundingClientRect().top + window.scrollY - offset;

    window.scrollTo({ top: Math.max(0, Math.round(top)), behavior: reduced ? 'auto' : 'smooth' });

    // Keep the URL honest without letting the browser jump as well.
    if (window.history?.replaceState) window.history.replaceState(null, '', `#${id}`);

    // Move focus so the jump is not purely visual.
    const focusable = target.hasAttribute('tabindex') ? target : null;
    if (!focusable) target.setAttribute('tabindex', '-1');
    target.focus({ preventScroll: true });
    if (!focusable) target.removeAttribute('tabindex');
  };

  root.addEventListener('click', onClick);
  return () => root.removeEventListener('click', onClick);
}

/** Header: compact state after the hero, plus active-section marking. */
function initHeader() {
  const header = q('[data-rv-header]');
  if (!header) return;

  const sentinel = document.createElement('div');
  sentinel.style.cssText = 'position:absolute;top:0;left:0;width:1px;height:80vh;pointer-events:none;';
  siteRoot().prepend(sentinel);

  new IntersectionObserver(
    ([entry]) => header.classList.toggle('is-stuck', !entry.isIntersecting),
    { threshold: 0 }
  ).observe(sentinel);

  const links = qa('.rv-nav__link');
  const targets = links
    .map((link) => {
      const id = link.getAttribute('href')?.slice(1);
      const el = id && siteRoot().querySelector(`#${CSS.escape(id)}`);
      return el ? { link, el } : null;
    })
    .filter(Boolean);

  if (!targets.length) return;

  const spy = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        const match = targets.find((t) => t.el === entry.target);
        if (!match) return;
        links.forEach((l) => l.classList.remove('is-active'));
        match.link.classList.add('is-active');
      });
    },
    { rootMargin: '-45% 0px -50% 0px' }
  );

  targets.forEach((t) => spy.observe(t.el));
}

/* ---- src/js/interactions.js --------------------------------------------- */
/**
 * Pointer-driven interactions and scene transformation.
 *
 * Everything here is namespaced to the RENUVOL markup and attaches only to
 * elements it finds, so any single section can be lifted out (see
 * docs/tilda-integration.md) without breaking the rest.
 */

const isFinePointer = () =>
  window.matchMedia('(hover: hover) and (pointer: fine)').matches &&
  !window.matchMedia('(prefers-reduced-motion: reduce)').matches;

/* ---------- Pointer parallax ------------------------------------------------
   Publishes a normalised pointer position (-1..1) so any element carrying
   .rv-pointer can respond in CSS. Fine pointers only, and never under
   reduced motion. */

function initPointer() {
  if (!isFinePointer()) return;

  const root = siteRoot();
  let pending = 0;
  let x = 0;
  let y = 0;

  window.addEventListener(
    'pointermove',
    (event) => {
      x = (event.clientX / window.innerWidth) * 2 - 1;
      y = (event.clientY / window.innerHeight) * 2 - 1;
      if (pending) return;
      pending = requestAnimationFrame(() => {
        pending = 0;
        root.style.setProperty('--rv-mx', x.toFixed(3));
        root.style.setProperty('--rv-my', y.toFixed(3));
      });
    },
    { passive: true }
  );
}

/* ---------- 04 · Formula orbit -------------------------------------------- */

/** Ingredient identities. One colour drives the whole scene per selection. */
const INGREDIENT_TINT = {
  pdo: 'var(--rv-a-pdo)',
  pn: 'var(--rv-a-pn)',
  vitc: 'var(--rv-a-vitc)',
  gsh: 'var(--rv-a-gsh)',
  ha: 'var(--rv-a-ha)',
};

function initFormula() {
  const root = q('[data-rv-formula]');
  if (!root) return;

  const section = root.closest('[data-rv-scene]');
  const nodes = Array.from(root.querySelectorAll('[data-rv-node]'));
  const panels = Array.from(root.querySelectorAll('[data-rv-panel]'));
  const links = Array.from(root.querySelectorAll('[data-rv-link]'));
  if (!nodes.length || !panels.length) return;

  let active = nodes[0].dataset.rvNode;

  function setActive(key) {
    if (key === active) return;
    active = key;

    nodes.forEach((node) => node.setAttribute('aria-pressed', String(node.dataset.rvNode === key)));
    links.forEach((line) => line.classList.toggle('is-active', line.dataset.rvLink === key));
    panels.forEach((panel) => {
      panel.hidden = panel.dataset.rvPanel !== key;
    });

    // Selecting an ingredient transforms the scene, not just the text: the
    // halo, the wash across the product, the connector and the heading all
    // read from this one value.
    if (section && INGREDIENT_TINT[key]) {
      section.style.setProperty('--rv-active', INGREDIENT_TINT[key]);
    }
  }

  nodes.forEach((node) => {
    const key = node.dataset.rvNode;
    node.addEventListener('click', () => setActive(key));
    node.addEventListener('focus', () => setActive(key));
    if (isFinePointer()) {
      node.addEventListener('pointerenter', () => setActive(key));
    }
  });

  links.forEach((line) => line.classList.toggle('is-active', line.dataset.rvLink === active));
  if (section && INGREDIENT_TINT[active]) {
    section.style.setProperty('--rv-active', INGREDIENT_TINT[active]);
  }

  buildFormulaAccordion(root, panels, nodes);
}

/**
 * Below the orbit breakpoint the five components become a native accordion.
 * The panels are reused rather than duplicated, so there is one source of
 * content for both presentations.
 */
function buildFormulaAccordion(root, panels, nodes) {
  const detail = root.querySelector('[data-rv-detail]');
  const cta = detail?.querySelector('.rv-detail__cta');
  if (!detail || detail.querySelector('.rv-accordion')) return;

  const mq = window.matchMedia('(max-width: 860px)');
  let accordion = null;

  const build = () => {
    if (accordion) return;
    accordion = document.createElement('div');
    accordion.className = 'rv-accordion';

    panels.forEach((panel, index) => {
      const key = panel.dataset.rvPanel;
      const node = nodes.find((n) => n.dataset.rvNode === key);
      const name = node?.querySelector('.rv-node__name')?.textContent?.trim() || key;
      const indexLabel = panel.querySelector('.rv-detail__index')?.textContent?.trim() || '';

      const item = document.createElement('div');
      item.className = 'rv-accordion__item';
      item.dataset.rvAccent = panel.dataset.rvAccent || '';
      if (index === 0) item.classList.add('is-open');

      const trigger = document.createElement('button');
      trigger.type = 'button';
      trigger.className = 'rv-accordion__trigger';
      trigger.setAttribute('aria-expanded', index === 0 ? 'true' : 'false');
      trigger.innerHTML =
        '<span class="rv-accordion__lead">' +
        `<span class="rv-accordion__dot" aria-hidden="true"></span>` +
        `<span class="rv-node__index">${indexLabel}</span>` +
        '<span class="rv-node__name"></span>' +
        '</span><span class="rv-accordion__sign" aria-hidden="true"></span>';
      trigger.querySelector('.rv-node__name').textContent = name;

      const body = document.createElement('div');
      body.className = 'rv-accordion__body';
      const inner = document.createElement('div');
      inner.className = 'rv-accordion__inner';
      body.append(inner);

      trigger.addEventListener('click', () => {
        const open = item.classList.toggle('is-open');
        trigger.setAttribute('aria-expanded', String(open));
      });

      item.append(trigger, body);
      accordion.append(item);
      inner.append(panel);
      panel.hidden = false;
    });

    detail.prepend(accordion);
    if (cta) detail.append(cta);
  };

  const teardown = () => {
    if (!accordion) return;
    panels.forEach((panel) => detail.insertBefore(panel, accordion));
    accordion.remove();
    accordion = null;
    const first = nodes.find((n) => n.getAttribute('aria-pressed') === 'true') || nodes[0];
    panels.forEach((panel) => {
      panel.hidden = panel.dataset.rvPanel !== first.dataset.rvNode;
    });
  };

  const apply = () => (mq.matches ? build() : teardown());
  apply();
  mq.addEventListener('change', apply);
}

/* ---------- 05 · Before / after comparison --------------------------------- */

function initCompare() {
  const root = q('[data-rv-compare]');
  if (!root) return;

  const input = root.querySelector('[data-rv-compare-input]');
  if (!input) return;

  const apply = (value) => root.style.setProperty('--rv-split', `${value}%`);

  apply(input.value);
  input.addEventListener('input', () => apply(input.value));

  // Dragging anywhere on the frame moves the split, not just the handle.
  let dragging = false;

  const positionFrom = (clientX) => {
    const rect = root.getBoundingClientRect();
    const ratio = ((clientX - rect.left) / rect.width) * 100;
    const clamped = Math.min(100, Math.max(0, ratio));
    input.value = String(clamped);
    apply(clamped);
  };

  root.addEventListener('pointerdown', (event) => {
    dragging = true;
    root.setPointerCapture?.(event.pointerId);
    positionFrom(event.clientX);
  });

  root.addEventListener('pointermove', (event) => {
    if (!dragging) return;
    positionFrom(event.clientX);
  });

  const stop = (event) => {
    if (!dragging) return;
    dragging = false;
    root.releasePointerCapture?.(event.pointerId);
  };

  root.addEventListener('pointerup', stop);
  root.addEventListener('pointercancel', stop);
}

/* ---------- 06 · Chapter rail + the evolving form --------------------------- */

/**
 * Five states of one form. The rail's progress selects the state, so the
 * central sculpture is the section's protagonist and the chapters are its
 * captions.
 */
const MORPH_STATES = [
  // Увлажнение — liquid, luminous, full
  { tint: 'var(--rv-a-ha)', radius: '50%', scale: 1, stretch: 1, ring: 1, core: 0.9 },
  // Плотность — compressed, denser, tighter
  { tint: 'var(--rv-a-pdo)', radius: '44% 44% 40% 40% / 46% 46% 42% 42%', scale: 0.92, stretch: 0.82, ring: 0.86, core: 0.55 },
  // Эластичность — stretched
  { tint: 'var(--rv-a-pn)', radius: '52% 48% 46% 54% / 58% 54% 46% 42%', scale: 1.04, stretch: 1.22, ring: 1.1, core: 0.6 },
  // Рельеф — refined, smoothed
  { tint: 'var(--rv-a-gsh)', radius: '50%', scale: 0.98, stretch: 1, ring: 0.94, core: 0.42 },
  // Glow — brightest, iridescent
  { tint: 'var(--rv-a-vitc)', radius: '50%', scale: 1.14, stretch: 1, ring: 1.24, core: 1 },
];

function initRail({ engine }) {
  const rail = q('[data-rv-rail]');
  const scene = rail?.closest('[data-rv-scene]');
  if (!rail || !scene || !engine) return;

  const stage = scene.querySelector('[data-rv-stage]') || scene;
  const chapters = Array.from(rail.querySelectorAll('.rv-chapter'));
  const mq = window.matchMedia('(max-width: 860px)');
  let travel = 0;
  let state = -1;

  const measure = () => {
    if (mq.matches) {
      travel = 0;
      rail.style.removeProperty('--rv-rail-x');
      return;
    }
    // Measure real overflow rather than assuming it: a rail narrower than the
    // viewport would otherwise pin a motionless screen for its whole span.
    travel = Math.max(rail.scrollWidth - window.innerWidth, 0);
  };

  const setState = (index) => {
    if (index === state) return;
    state = index;
    const s = MORPH_STATES[index] || MORPH_STATES[0];
    stage.style.setProperty('--rv-stage-tint', s.tint);
    stage.style.setProperty('--rv-morph-radius', s.radius);
    stage.style.setProperty('--rv-morph-scale', String(s.scale));
    stage.style.setProperty('--rv-morph-stretch', String(s.stretch));
    stage.style.setProperty('--rv-morph-ring', String(s.ring));
    stage.style.setProperty('--rv-morph-core', String(s.core));

    chapters.forEach((chapter, i) => {
      chapter.style.opacity = i === index ? '1' : '0.36';
    });
  };

  measure();
  setState(0);
  window.addEventListener('resize', measure, { passive: true });
  mq.addEventListener('change', measure);

  engine.onProgress((sceneEl, p) => {
    if (sceneEl !== scene) return;
    if (travel) rail.style.setProperty('--rv-rail-x', `${(-travel * p).toFixed(1)}px`);
    // Progress selects which of the five states the form is in.
    setState(Math.min(MORPH_STATES.length - 1, Math.floor(p * MORPH_STATES.length)));
  });

  // On touch the rail scrolls natively, so the state follows that scroll.
  rail.addEventListener(
    'scroll',
    () => {
      if (!mq.matches) return;
      const max = rail.scrollWidth - rail.clientWidth;
      if (max <= 0) return;
      const p = rail.scrollLeft / max;
      setState(Math.min(MORPH_STATES.length - 1, Math.round(p * (MORPH_STATES.length - 1))));
    },
    { passive: true }
  );
}

/* ---------- 12 · Private selection + form ---------------------------------- */

function initSelection() {
  const root = q('[data-rv-selection]');
  if (!root) return;

  const buttons = Array.from(root.querySelectorAll('[data-rv-profile]'));
  const panel = root.querySelector('[data-rv-private]');
  const choice = root.querySelector('[data-rv-private-choice]');
  const field = q('[data-rv-profile-field]');

  buttons.forEach((button) => {
    button.addEventListener('click', () => {
      const value = button.dataset.rvProfile || '';
      buttons.forEach((b) => b.setAttribute('aria-pressed', String(b === button)));
      if (choice) choice.textContent = value;
      if (field) field.value = value;
      if (panel) panel.hidden = false;
    });
  });
}

function initForm() {
  const form = q('[data-rv-form]');
  if (!form) return;

  const status = form.querySelector('[data-rv-form-status]');

  const messages = {
    name: 'Укажите имя',
    contact: 'Укажите телефон или Telegram',
    email: 'Укажите корректный e-mail',
    consent: 'Необходимо согласие на обработку данных',
  };

  const fieldWrap = (input) => input.closest('.rv-field') || input.closest('.rv-consent');

  const setError = (input, message) => {
    const wrap = fieldWrap(input);
    const slot = wrap?.querySelector('[data-rv-error]');
    if (slot) slot.textContent = message || '';
    wrap?.classList.toggle('is-invalid', Boolean(message));
    if (message) input.setAttribute('aria-invalid', 'true');
    else input.removeAttribute('aria-invalid');
  };

  const validate = () => {
    let firstInvalid = null;

    form.querySelectorAll('input, textarea').forEach((input) => {
      if (!input.name || !input.required) return;
      let message = '';

      if (input.type === 'checkbox') {
        if (!input.checked) message = messages[input.name] || 'Заполните поле';
      } else if (!input.value.trim()) {
        message = messages[input.name] || 'Заполните поле';
      } else if (input.type === 'email' && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input.value.trim())) {
        message = messages.email;
      }

      setError(input, message);
      if (message && !firstInvalid) firstInvalid = input;
    });

    return firstInvalid;
  };

  form.addEventListener('submit', async (event) => {
    event.preventDefault();

    const invalid = validate();
    if (invalid) {
      invalid.focus();
      if (status) status.textContent = 'Проверьте выделенные поля.';
      return;
    }

    const endpoint = form.dataset.rvEndpoint;
    const payload = Object.fromEntries(new FormData(form).entries());

    // No endpoint is configured yet: the integration target is a deployment
    // decision (Tilda handler, webhook or CRM) — see docs/tilda-integration.md.
    if (!endpoint) {
      form.dispatchEvent(new CustomEvent('rv:submit', { detail: payload, bubbles: true }));
      if (status) status.textContent = 'Спасибо. Мы свяжемся с вами.';
      return;
    }

    if (status) status.textContent = 'Отправляем…';

    try {
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      if (!response.ok) throw new Error(String(response.status));
      form.reset();
      if (status) status.textContent = 'Заявка отправлена. Мы свяжемся с вами.';
    } catch {
      if (status) status.textContent = 'Не удалось отправить заявку. Попробуйте ещё раз.';
    }
  });

  form.querySelectorAll('input, textarea').forEach((input) => {
    input.addEventListener('input', () => setError(input, ''));
    input.addEventListener('change', () => setError(input, ''));
  });
}

/* ---------- Footer year ----------------------------------------------------- */

function initYear() {
  const slot = q('[data-rv-year]');
  if (slot) slot.textContent = String(new Date().getFullYear());
}

/* ---- src/js/mobile.js --------------------------------------------------- */
/**
 * Mobile behaviour.
 *
 * Not a scaled-down desktop: the menu and the swipeable carousel are
 * separate interactions that replace their desktop counterparts below the
 * breakpoint. See docs/mobile-spec.md.
 */

/** Burger menu with focus containment and scroll lock. */

function initMenu() {
  const burger = q('[data-rv-burger]');
  const menu = q('[data-rv-menu]');
  if (!burger || !menu) return;

  let open = false;
  let lastFocus = null;

  const setOpen = (next) => {
    open = next;
    burger.setAttribute('aria-expanded', String(open));
    burger.setAttribute('aria-label', open ? 'Закрыть меню' : 'Открыть меню');
    menu.hidden = !open;
    document.body.style.overflow = open ? 'hidden' : '';

    if (open) {
      lastFocus = document.activeElement;
      menu.querySelector('a, button')?.focus();
    } else if (lastFocus instanceof HTMLElement) {
      lastFocus.focus();
    }
  };

  burger.addEventListener('click', () => setOpen(!open));

  menu.addEventListener('click', (event) => {
    if (event.target instanceof HTMLAnchorElement) setOpen(false);
  });

  document.addEventListener('keydown', (event) => {
    if (!open) return;
    if (event.key === 'Escape') {
      setOpen(false);
      return;
    }
    if (event.key !== 'Tab') return;

    const focusable = menu.querySelectorAll('a[href], button:not([disabled])');
    if (!focusable.length) return;
    const first = focusable[0];
    const last = focusable[focusable.length - 1];

    if (event.shiftKey && document.activeElement === first) {
      event.preventDefault();
      last.focus();
    } else if (!event.shiftKey && document.activeElement === last) {
      event.preventDefault();
      first.focus();
    }
  });

  // Leaving mobile width with the menu open would otherwise strand the lock.
  window.matchMedia('(min-width: 1025px)').addEventListener('change', (event) => {
    if (event.matches && open) setOpen(false);
  });
}

/**
 * iOS viewport height: 100dvh is well supported now, but older Safari still
 * needs a measured fallback for the pinned stages.
 */
function initViewportUnit() {
  if (CSS.supports?.('height: 100dvh')) return;

  const set = () => {
    siteRoot().style.setProperty('--rv-vh', `${window.innerHeight * 0.01}px`);
    qa('[data-rv-stage]').forEach((stage) => {
      stage.style.height = `${window.innerHeight}px`;
    });
  };

  set();
  window.addEventListener('resize', set, { passive: true });
  window.addEventListener('orientationchange', set);
}

/* ---- src/js/video-modal.js ---------------------------------------------- */
/**
 * Optional film experience.
 *
 * The video is a secondary asset: its source is not attached until the
 * visitor opens the modal, so it costs nothing at first paint and the page
 * is complete without it. Nothing on the page depends on it loading.
 */

/**
 * Pick the best clip this browser can actually decode, at the right size for
 * the device. Some builds ship without the proprietary H.264 decoder, so this
 * is a capability check rather than a browser sniff.
 */
function pickSource(video, isTouch) {
  const d = video.dataset;
  const webm = (isTouch && d.rvSrcWebmMobile) || d.rvSrcWebm;
  const mp4 = (isTouch && d.rvSrcMobile) || d.rvSrc;

  if (webm && video.canPlayType('video/webm; codecs="vp9"')) return webm;
  if (mp4 && video.canPlayType('video/mp4; codecs="avc1.42E01E"')) return mp4;
  return mp4 || webm || '';
}

function initFilm() {
  const root = q('[data-rv-film]');
  const video = root?.querySelector('[data-rv-film-video]');
  const openers = qa('[data-rv-video-open]');
  if (!root || !video || !openers.length) return null;

  const dialog = root.querySelector('.rv-film__dialog');
  // The source clip closes on a third-party manufacturer end-card, which is
  // not ours to publish without a rights decision (docs/claims-verification.md).
  // Stop the film before it. Remove the attribute once the master is trimmed.
  const endAt = parseFloat(video.dataset.rvEnd || '');
  let lastFocus = null;
  let loaded = false;

  if (Number.isFinite(endAt)) {
    video.addEventListener('timeupdate', () => {
      if (video.currentTime >= endAt) {
        video.pause();
        video.currentTime = endAt;
      }
    });
  }

  const open = () => {
    lastFocus = document.activeElement;

    // Attach the source on first open only.
    if (!loaded) {
      const src = pickSource(video, window.matchMedia('(pointer: coarse)').matches);
      if (src) {
        video.src = src;
        loaded = true;
      }
    }

    root.hidden = false;
    document.body.style.overflow = 'hidden';
    root.querySelector('[data-rv-film-close]')?.focus();

    // Play on the visitor's action, never on load, and never with sound
    // they did not ask for.
    video.play().catch(() => {
      /* the controls are there if autoplay is refused */
    });
  };

  const close = () => {
    video.pause();
    if (Number.isFinite(endAt) && video.currentTime >= endAt) video.currentTime = 0;
    root.hidden = true;
    document.body.style.overflow = '';
    if (lastFocus instanceof HTMLElement) lastFocus.focus();
  };

  openers.forEach((btn) => btn.addEventListener('click', open));
  root.querySelectorAll('[data-rv-film-close]').forEach((el) =>
    el.addEventListener('click', close)
  );

  document.addEventListener('keydown', (event) => {
    if (root.hidden) return;

    if (event.key === 'Escape') {
      close();
      return;
    }
    if (event.key !== 'Tab' || !dialog) return;

    const focusable = dialog.querySelectorAll('button, video[controls], a[href]');
    if (!focusable.length) return;
    const first = focusable[0];
    const last = focusable[focusable.length - 1];

    if (event.shiftKey && document.activeElement === first) {
      event.preventDefault();
      last.focus();
    } else if (!event.shiftKey && document.activeElement === last) {
      event.preventDefault();
      first.focus();
    }
  });

  return { open, close };
}

/* ---- src/js/main.js ----------------------------------------------------- */
/**
 * RENUVOL — entry point.
 *
 * Initialisation is explicit and each module attaches only to the markup it
 * finds inside `#renuvol-site`, so sections can be moved or lifted out
 * individually (see docs/tilda-integration.md). Nothing is written to the
 * global scope beyond the single `window.RENUVOL` handle used for teardown.
 *
 * The boot sequence is written for the harder of the two environments. On a
 * Tilda page the block's markup can appear after DOMContentLoaded, after
 * `load`, or be re-rendered by the editor, so booting is:
 *
 *   - idempotent — a second call is a no-op while the same wrapper is live;
 *   - patient — it waits for the wrapper rather than assuming it exists;
 *   - self-checking — if `position: sticky` does not actually stick (a Tilda
 *     ancestor with a non-visible overflow will do that), the page falls back
 *     to the static layout it already has for reduced motion, instead of
 *     leaving four pinned scenes frozen on a dead scroll.
 */





let booted = null;

/**
 * Does `position: sticky` actually stick here?
 *
 * An ancestor with a non-visible `overflow` silently turns sticky into
 * static for everything below it, and a host page can introduce one at any
 * time — Tilda's own wrappers sometimes do. There is no feature query for
 * that, so walk the ancestors.
 *
 * `<html>` and `<body>` are excluded on purpose: their overflow propagates
 * to the viewport, which is the normal scrolling box, and sticky works
 * against it. This site's own `body { overflow-x: hidden }` is exactly that
 * case, and treating it as a blocker would put every visitor into the static
 * layout.
 */
function stickyWorks(root) {
  if (!CSS.supports?.('position', 'sticky')) return false;

  const body = document.body;
  for (let el = root.parentElement; el && el !== body; el = el.parentElement) {
    const style = getComputedStyle(el);
    if (style.overflow !== 'visible' || style.overflowX !== 'visible' || style.overflowY !== 'visible') {
      return false;
    }
  }
  return true;
}

/**
 * Initialise the site. Safe to call more than once and from any point in the
 * page lifecycle.
 *
 * @returns {object|null} the `window.RENUVOL` handle, or null if the wrapper
 *   is not in the document yet.
 */
function initRenuvolSite() {
  const root = document.getElementById('renuvol-site');
  if (!root) return null;

  // Already running against this same wrapper.
  if (booted && booted.root === root && root.isConnected) return booted.api;

  // A different wrapper (Tilda re-rendered the block): tear the old one down
  // rather than stacking a second set of listeners on top of it.
  if (booted) {
    booted.api.destroy();
    booted = null;
    resetSiteRoot();
  }

  if (root.dataset.rvBooted === 'true') return booted?.api ?? null;
  root.dataset.rvBooted = 'true';

  const prefersReduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const reducedMotion = prefersReduced || !stickyWorks(root);

  root.classList.remove('rv-no-js');

  // Layout and viewport first, so measured values are correct.
  initViewportUnit();

  const engine = createScrollEngine({ reducedMotion });

  initHeader();
  initAnchors();
  initReveals();
  initMenu();
  initPointer();

  initFormula();
  initCompare();
  initRail({ engine });

  initSelection();
  initForm();
  initYear();

  // The film is optional and loads nothing until it is opened.
  const film = initFilm();

  const api = {
    engine,
    film,
    root,
    reducedMotion,
    destroy() {
      engine.destroy();
      root.removeAttribute('data-rv-booted');
      booted = null;
      resetSiteRoot();
    },
  };

  booted = { root, api };
  window.RENUVOL = api;
  return api;
}

/**
 * Boot as soon as the wrapper exists.
 *
 * Tries immediately, then on DOMContentLoaded and `load`, and finally
 * observes the DOM for a short window — which covers a T123 block whose
 * markup is injected after both events have already fired.
 */
function autoBoot() {
  if (initRenuvolSite()) return;

  const attempt = () => Boolean(initRenuvolSite());

  document.addEventListener('DOMContentLoaded', attempt, { once: true });
  window.addEventListener('load', attempt, { once: true });

  if (typeof MutationObserver !== 'function') return;

  const observer = new MutationObserver(() => {
    if (attempt()) observer.disconnect();
  });
  observer.observe(document.documentElement, { childList: true, subtree: true });

  // Do not watch the host page forever.
  window.setTimeout(() => observer.disconnect(), 20000);
}

// The stylesheet hides cue content until the engine runs; if scripting is
// unavailable the class stays and CSS reveals everything instead. Applied to
// the wrapper as soon as it can be found, so nothing flashes.
(function markNoJs() {
  const apply = () => {
    const root = document.getElementById('renuvol-site');
    if (root) root.classList.add('rv-no-js');
    return Boolean(root);
  };
  if (!apply()) document.addEventListener('DOMContentLoaded', apply, { once: true });
})();

autoBoot();

if (typeof window !== 'undefined') {
  // Exposed so a Tilda page (or the editor's preview) can re-run the boot by
  // hand if a block is rebuilt.
  window.initRenuvolSite = initRenuvolSite;
}
})();
